-- Insert some default challenges for current month
INSERT INTO scoreboards_challenges_service.challenges (title, description, month, year) VALUES 

    ('Distance Runner', 'Complete 50km of total hiking distance', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Altitude Hunter', 'Reach 1000m elevation gain in a single hike', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Night Owl', 'Complete a night hike with headlamp', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Summit Seeker', 'Reach the summit of 10 different peaks', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Photo Explorer', 'Take 50 unique hiking photos', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Group Hiker', 'Complete 4 group hikes', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Fitness Fanatic', 'Hike 5 times per week', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Time Keeper', 'Complete a hike in under 2 hours', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Endurance Champion', 'Complete a 6+ hour hike', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Nature Lover', 'Visit 5 different natural landmarks', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('All Weather Hiker', 'Hike in 3 different weather conditions', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Scenic Route', 'Complete the 5 most popular trails', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Elevation Master', 'Accumulate 5000m elevation gain this month', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Hidden Gem Finder', 'Discover 3 lesser-known trails', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Consistency Champion', 'Hike on 20 different days this month', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Speed Demon', 'Complete a hike faster than your personal best', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Wildlife Spotter', 'Spot and photograph 3 different wildlife species', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Trail Variety', 'Complete hikes of 4 different difficulty levels', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Morning Glory', 'Complete 5 hikes starting before noon', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Sunset Chaser', 'Finish a hike with a sunset view', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Challenge Collector', 'Complete 10 different challenges this month', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Friend Recruiter', 'Invite 3 new people to join your hikes', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Milestone Maker', 'Log your 100th hike', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Budget Hiker', 'Complete a hike with gear weighing less than 5kg', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Explorers Spirit', 'Complete hikes in 5 different regions', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE)),
    ('Technical Climber', 'Complete a trail with rock scrambling sections', EXTRACT(MONTH FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE));
