replicaCount: 1

image:
  repository: scoreboards-challenges-service
  tag: dev-latest
  pullPolicy: Never

database:
  enabled: true
  host: postgres.database.svc.cluster.local
  port: "5432"
  name: hikudb
  schema: scoreboards_challenges_service

azure:
  enabled: false

service:
  clusterIP:
    port: 8089

  nodePort:
    enabled: true
    port: 8089
    nodePort: 30089

flyway:
  image:
    repository: scoreboards-challenges-service-migrator
    tag: "dev"

jwtAuth:
  issuer: "http://localhost:8080/auth/realms/hiku-dev"
  jwksUri: "http://keycloak.keycloak.svc.cluster.local:8080/auth/realms/hiku-dev/protocol/openid-connect/certs"